[package]
name = "trenitalia"
version = "0.1.0"
authors = ["Eugenio Tampieri <eugenio.tampieri@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.10"
drs-primitives = { git = "https://github.com/eutampieri/drs-primitives" }
