[package]
name = "trenitalia"
version = "0.1.0"
authors = ["Eugenio Tampieri <eugenio.tampieri@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
drs_primitives = { git = "https://github.com/eutampieri/drs-primitives" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
diff = "0.1"